version: 2.1

jobs:
  relyance: 
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
          
      - run: echo "Build job ran successfully."

workflows:
  version: 2.1

  all:
    jobs:
      - relyance